import subprocess

child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate('Why is the parson paying a visit to the Butler family home?')
child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate('Did Cuyloga swear when he was a boy? How did he learn how to curse? Why did he stop swearing?')
child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate('Who was Colonel Elder and what role did he play in the conflict between the Conestogo and Peshtank men?')
child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate('What excuse does the parson offer True Son for not stopping the massacre?')
child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate("How does Doctor Childsley treat True Son's illness? ")
child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate("The doctor does not successfully diagnose True Son's illness, but he has some theories about what is wrong with the boy and why he is so sick.")
child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate('As he looks in on his sick son, Harry Butler expresses to himself a sincere wish. What is it, and why does it, at this point in the story, appear unlikely to come true?')
child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate("Who arrives at the Butler home shortly after Mr. Butter leaves his son's room? What disturbing news does he bring?")
child = subprocess.Popen(['python', 'main.py'], stdin=subprocess.PIPE)
child.communicate('What specific activity does Harry Butler engage in to relieve stress? Why is this helpful and reassuring to him? Does this make sense to you? Why or why not?')